import React from 'react';
import Head from 'next/head';
import { Inter } from 'next/font/google';
import "../../styles/globals.css";
import Header from './header'; // Make sure the path is correct
import Footer from './footer'; // Make sure the path is correct

// Apply the Inter font family by calling the imported `Inter` function.
const interFont = Inter({ subsets: ['latin'] });

const RootLayout: React.FC<{ children: React.ReactNode }> = ({ children }) => {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <style>{interFont}</style> {/* This will inject the font styles */}
            </Head>
            <div className={interFont.className}>
                <Header />
                <main>{children}</main>
                <Footer />
            </div>
        </>
    );
};

export default RootLayout;
